name: deepinvhessian
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.11.5
  - pip
  - numpy
  - scipy
  - matplotlib
  - cuda-version=11.8
  - pylops
  - pytorch-cuda=11.8
  - torchvision
  - ipython
  - jupyter
  - tqdm
  - scikit-image
  - pip:
    - deepwave
    - opencv-python
    - setuptools_scm
