name: deepinvhessian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy>=1.23.5
  - scipy==1.9.3
  - cudatoolkit=11.3
  - pytorch==1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - matplotlib==3.5.1
  - ipython
  - jupyter
  - tqdm==4.64.0
  - pip:
    - setuptools_scm
    - torchsummary
    - deepwave==0.0.9
    - pylops

