name: deepinvhessian
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cuda
  - cudatoolkit=12.3
  - jupyter
  - matplotlib
  - numpy
  - opencv
  - pip
  - pylops
  - python
  - pytorch
  - scikit-image
  - scipy
  - torchvision 
  - pip:
    - deepwave
    - notebook
    - setuptools_scm
    - tqdm