FWI_itr: 100
batch_size: 1
dr: 10
ds: 100
dt: 0.004
dx: 5.0
dz: 5.0
freq: 5
fwi_pass: 1
nr: 250
ns: 25
nt: 500
num_batches: 25
num_dims: 2
nx: 500
nz: 251
orec: 0
osou: 50
ot: 0
ox: 0
oz: 0
rz: 0
sz: 0
vel_true: ../data/SEAM_Vp_Elastic_N23900_chop.bin
vel_true_path: ''
